### ISSUE TITLE
I'm getting expected element type <MediaContainer> but have <Error>

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [pyang55/oversaw#1]
```
Running a Overseer Search

expected element type <MediaContainer> but have <Error>

expected element type <MediaContainer> but have <Error>

Running a Overseer Search
```

When I go to https://metadata.provider.plex.tv/library/sections/watchlist/all?X-Plex-Token=[TOKEN]
I get ```<Error error="Unauthorized" message="Response code 401 (Unauthorized)" statusCode="401"/>```

**Comment by cookie-monster-bit** [comment]
I used a different token and it works now!
